server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sdu_story_game?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto


app:
  jwt:
    secret: sdustorygame2026selfbackendloginkey
    expire: 604800000
  cas:
    # 统一认证Pass平台的基础地址
    base-url: https://i.sdu.edu.cn/pass-api
    # 控制台创建JWT应用后拿到的JWT密钥
    # 用于对官方换回的JWT做PBKDF2派生+HS256验签
    jwt-secret: dev-placeholder
    # 前端
    frontend-url: http://localhost:5173/login-success
    # 是否开启 mock，测试开发开启
    mock-enabled: true
